# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
# you can use 'mic' to control your mic input level (uses the default recording device)
# you can use 'deej.unmapped' to control all apps that aren't bound to any slider (this ignores master, system, mic and device-targeting sessions) (experimental)
# windows only - you can use 'deej.current' to control the currently active app (whether full-screen or not) (experimental)
# windows only - you can use a device's full name, i.e. "Speakers (Realtek High Definition Audio)", to bind it. this works for both output and input devices
# windows only - you can use 'system' to control the "system sounds" volume
# important: slider indexes start at 0, regardless of which analog pins you're using!
slider_mapping:
  0: master
  1: deej.unmapped
  2: Spotify.exe
  3:
    - pathofexile_x64.exe
    - FortniteClient-Win64-Shipping.exe
    - GTA5.exe
    - rocketleague.exe
    - Cyberpunk2077.exe
    - re8.exe
    - BatmanAK.exe
    - GhostOfTsushima.exe
    - WWE2K24_x64.exe
    - MK11.exe
    - Injustice2.exe
    - DOOMEternalx64vk.exe
    - GoW.exe
    - GoWR.exe
    - HogwartsLegacy.exe
    - tll.exe
    - VALORANT-Win64-Shipping.exe
    - SOTTR.exe
    - ForzaHorizon4.exe
    - SuicideSquad_KTJL.exe
    - rpcs3.exe
    - re7.exe
  4: discord.exe

# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: false

# settings for connecting to the arduino board
com_port: COM7
baud_rate: 9600

# adjust the amount of signal noise reduction depending on your hardware quality
# supported values are "low" (excellent hardware), "default" (regular hardware) or "high" (bad, noisy hardware)
noise_reduction: default

#master is a special option to control the master volume of the system (uses the default playback device)
#mic is a special option to control your microphone's input level (uses the default recording device)
#deej.unmapped is a special option to control all apps that aren't bound to any slider ("everything else")
#On Windows, deej.current is a special option to control whichever app is currently in focus
#On Windows, you can specify a device's full name, i.e. Speakers (Realtek High Definition Audio), to bind that device's level to a slider. This doesn't conflict with the default master and mic options, and works for both input and output devices.
#Be sure to use the full device name, as seen in the menu that comes up when left-clicking the speaker icon in the tray menu
#system is a special option on Windows to control the "System sounds" volume in the Windows mixer
#All names are case-insensitive, meaning both chrome.exe and CHROME.exe will work
#You can create groups of process names (using a list) to either:
#control more than one app with a single slider
#choose whichever process in the group that's currently running (i.e. to have one slider control any game you're playing)